### ISSUE TITLE
Update icons to latest collection

### ISSUE THREAD

**Issue by trevorgreenleaf** [denali-design/Denali#111]
Refresh and update our project's icons by integrating the latest icon collection. This update aims to enhance the visual appeal, consistency, and usability of our user interface by incorporating modern, high-quality icons.

- [ ] Add updated icons to icon directory (some icons need to be replaced others are brand new)
- [ ] Add updated icons to storybook icons page

**Comment by PeterMedina** [comment]
Updated icons added to project; Storybook icons list updated.
